spring.application.name=traceops

# Load variables from .env
spring.config.import=optional:file:.env[.properties]

# Neo4j
spring.neo4j.uri=${COGNODB_URI}
spring.neo4j.authentication.username=${COGNODB_USERNAME}
spring.neo4j.authentication.password=${COGNODB_PASSWORD}
spring.neo4j.database=${COGNODB_DATABASE}